
package testservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import testserviceschema.ObjectFactory;
import testserviceschema.TestRequestType;
import testserviceschema.TestResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4.1-hudson-346-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TestService_PortType", targetNamespace = "urn:TestService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestServicePortType {


    /**
     * 
     * @param request
     * @return
     *     returns testserviceschema.TestResponseType
     */
    @WebMethod(operationName = "DoSomething", action = "http://www.oasis-open.org/committees/security")
    @WebResult(name = "TestResponse", targetNamespace = "urn:TestServiceSchema", partName = "Response")
    public TestResponseType doSomething(
        @WebParam(name = "TestRequest", targetNamespace = "urn:TestServiceSchema", partName = "Request")
        TestRequestType request);

}
